---
# MOTD vars
system: Home

# Generic vars
enable_epel: true

# Hardening overrides
ssh_MaxAuthTries: 4
ssh_PermitRootLogin: 'yes'

# RHEL systems need a CDN/Satellite registration
register_with_cdn: true
cdn_user: geoff@gatwards.org
cdn_password: "{{ vault_cdn_password }}"
reset_redhat_repos: no

# Set our NTP servers
ntpservers:
  - ntp1.core.home.gatwards.org
  - ntp2.core.home.gatwards.org
  - ntp3.core.home.gatwards.org

# User Authentication via IPA
# auth_idm: true
# auth_idm_realm: IPA.HOME.GATWARDS.ORG
idm_admin_user: admin
idm_admin_pass: "{{ vault_idm_admin_pass }}"

# ipaclient_server: "ipa1.ipa.home.gatwards.org"
# ipaclient_domain: "{{ auth_idm_realm }}"
# ipaclient_enroll_user: "{{ idm_admin_user }}"
# ipaclient_enroll_pass: "{{ vault_idm_admin_pass }}"
# ipaclient_validate_certs: False
# ad_domain: AD.HOME.GATWARDS.ORG
# ad_via_ipa: true

# ldap_servers:
#   - ipa1.ipa.home.gatwards.org
#   - ipa2.ipa.home.gatwards.org

# ldap_user_base: 'CN=users,CN=accounts,DC=gatwards,DC=org'
# ldap_user_filter: '(uid=%(user)s)'
# ldap_group_base: 'CN=groups,CN=accounts,DC=gatwards,DC=org'
# ldap_group_filter: '(objectClass=ipausergroup)'

latitude: "{{ vault_latitude }}"
longitude: "{{ vault_longitude }}"

mqtt_broker_fqdn: automation.core.home.gatwards.org
