---
# MOTD vars
system: Home

# CIS Hardening
cis_level_1_exclusions: ['1.2.3','1.3.1','1.8','3.4.1','3.4.2','3.4.3','3.4.4','3.4.5','5.3.2']
cis_local_login_warning_banner: |
  ###############################################################
  #  All connections to this system are monitored and recorded  #
  #  Disconnect IMMEDIATELY if you are not an authorized user!  #
  ###############################################################
cis_remote_login_warning_banner: "{{ cis_local_login_warning_banner }}"
cis_chrony_servers: |+
  server ntp1.core.home.gatwards.org iburst
  server ntp2.core.home.gatwards.org iburst
  server ntp3.core.home.gatwards.org iburst



# Generic vars
enable_epel: true

# RHEL systems need a CDN/Satellite registration
register_with_cdn: true
cdn_user: geoff@gatwards.org
cdn_password: "{{ vault_cdn_password }}"
reset_redhat_repos: no




# LDAP configs for non-IdM apps
ldap_servers:
  - ipa1.ipa.home.gatwards.org
  - ipa2.ipa.home.gatwards.org
ldap_user_base: 'CN=users,CN=accounts,DC=gatwards,DC=org'
ldap_user_filter: '(uid=%(user)s)'
ldap_group_base: 'CN=groups,CN=accounts,DC=gatwards,DC=org'
ldap_group_filter: '(objectClass=ipausergroup)'



# Location parameters used in multple groups
latitude: "{{ vault_latitude }}"
longitude: "{{ vault_longitude }}"
altitude: '698'

# Common SSL parameters
tls_cafile: /etc/pki/ca-trust/source/anchors/GatwardIT-IPA.pem

# InfluxDB is used by multiple groups, common params defined here
influxdb_admin_password: "{{ vault_influxdb_admin_password }}"
influxdb_enable_ssl: true
influxdb_http_port: '8086'



# Open Grafana port
grafana_open_firewall: true

# MQTT broker is used by multiple groups, common params defined here
mqtt_broker_fqdn: automation.core.home.gatwards.org
mqtt_broker_port: '1883'
