---
# MOTD vars
system: Home

# Generic vars
enable_epel: true

# Hardening role overrides
ssh_MaxAuthTries: 4
ssh_PermitRootLogin: 'yes'

# RHEL systems need a CDN/Satellite registration
register_with_cdn: true
cdn_user: geoff@gatwards.org
cdn_password: "{{ vault_cdn_password }}"
reset_redhat_repos: no

# Define our NTP servers
ntpservers:
- ntp1.core.home.gatwards.org
- ntp2.core.home.gatwards.org
- ntp3.core.home.gatwards.org

# Common IdM parameters
# auth_idm: true
idm_realm: IPA.HOME.GATWARDS.ORG
idm_admin_user: admin
idm_admin_pass: "{{ vault_idm_admin_pass }}"

# ipaclient_server: "ipa1.ipa.home.gatwards.org"
# ipaclient_domain: "{{ auth_idm_realm }}"
# ipaclient_enroll_user: "{{ idm_admin_user }}"
# ipaclient_enroll_pass: "{{ vault_idm_admin_pass }}"
# ipaclient_validate_certs: False
# ad_domain: AD.HOME.GATWARDS.ORG
# ad_via_ipa: true

idmap_domain: 'home.gatwards.org'


# ldap_servers:
#   - ipa1.ipa.home.gatwards.org
#   - ipa2.ipa.home.gatwards.org
# ldap_user_base: 'CN=users,CN=accounts,DC=gatwards,DC=org'
# ldap_user_filter: '(uid=%(user)s)'
# ldap_group_base: 'CN=groups,CN=accounts,DC=gatwards,DC=org'
# ldap_group_filter: '(objectClass=ipausergroup)'



# Location parameters used in multple groups
latitude: "{{ vault_latitude }}"
longitude: "{{ vault_longitude }}"
altitude: '698'

# Common SSL parameters
tls_cafile: /etc/pki/ca-trust/source/anchors/GatwardIT-IPA.pem

# InfluxDB is used by multiple groups, common params defined here
influxdb_admin_password: "{{ vault_influxdb_admin_password }}"
influxdb_enable_ssl: true
influxdb_http_port: '8086'

# Prometheus common params
prometheus_remote_write:
- url: https://{{ influxdb_host }}:{{ influxdb_http_port }}/api/v1/prom/write?db=prometheus
  basic_auth:
    username: 'prometheus'
    password: "{{ vault_influxdb_prometheus_password }}"

# MQTT broker is used by multiple groups, common params defined here
mqtt_broker_fqdn: automation.core.home.gatwards.org
mqtt_broker_port: '1883'
