---
# MOTD vars
sys_env: LAB

# InfluxDB
influxdb_host: "influxdb.lab.home.gatwards.org"

# Prometheus parameters
prometheus_external_labels:
  environment: "LAB"

prometheus_targets:
  node:
  - targets:
    - "{{ ansible_fqdn }}:9100"
    labels:
      env: LAB

prometheus_static_targets_files:
  - prometheus/targets/lab.json


# Figure out how to dynamically update the target.json list.....
prometheus_scrape_configs:
  - job_name: "prometheus"
    metrics_path: "{{ prometheus_metrics_path }}"
    static_configs:
      - targets:
          - "{{ ansible_fqdn | default(ansible_host) | default('localhost') }}:9090"
  - job_name: "node"
    file_sd_configs:
      - files:
          - "{{ prometheus_config_dir }}/file_sd/node.yml"
          - "{{ prometheus_config_dir }}/file_sd/lab.json"
