# Postgresql
openhab_db_user: openhab2
openhab_db_password: "{{ vault_openhab_db_password }}"
openhab_db_name: openhab2
openhab_db_host: 127.0.0.1
postgresql_pgdata: /var/lib/pgsql/data

# MQTT defaults
# mqtt_broker: broker
# mqtt_host: localhost

mqtt_users:
  - user: openhab2
    pass: "{{ vault_openhab_mqtt_password }}"
  - user: weewx
    pass: "{{ vault_weewx_mqtt_pass }}"
  - user: bomxml
    pass: "{{ vault_bomxml2mqtt_pass }}"


# # Get sensitive vars from the vault

# #weewx_latitude: "{{ latitude }}"
# #weewx_longitude: "{{ longitude }}"


# openhab_voicerss_api_key: "{{ vault_oh2_voicerss_api_key }}"
# openhab_latlon: "{{ vault_oh2_latlon }}"

# sonos_ids:
#   livingroom: "{{ vault_sonos_livingroom }}"
#   alfresco: "{{ vault_sonos_alfresco }}"
#   annasroom: "{{ vault_sonos_annasroom }}"
#   office: "{{ vault_sonos_office }}"

# elk_ip: 172.22.2.10
# elk_port: 2101
