---
role: Home Automation Server

# Hardening Overrides
net_ipv4_ip_forward: 1

# Postgresql
openhab_db_user: openhab2
openhab_db_password: "{{ vault_openhab_db_password }}"
openhab_db_name: openhab2
openhab_db_host: 127.0.0.1
postgresql_pgdata: /var/lib/pgsql/data

# InfluxDB
influx_admin_password: "{{ vault_influx_admin_password }}"
openhab_influx_password: "{{ vault_openhab_influx_password }}"
openhab_grafana_influx_password: "{{ vault_openhab_grafana_influx_password }}"

# MQTT defaults
mqtt_use_ssl: true
#mqtt_broker_owntracks: false
mqtt_broker_tls_cafile: "{{ tls_cafile }}"
mqtt_broker_tls_cert: /etc/pki/tls/certs/{{ ansible_fqdn }}.pem
mqtt_broker_tls_key: /etc/pki/tls/private/{{ ansible_fqdn }}.key

mqtt_users:
  - user: openhab2
    pass: "{{ vault_openhab_mqtt_password }}"
  # - user: bomxml
  #   pass: "{{ vault_bomxml2mqtt_pass }}"
  # - user: irrigation1
  #   pass: "{{ vault_irrigation1_mqtt_password }}"

# # Get sensitive vars from the vault

openhab_voicerss_api_key: "{{ vault_openhab_voicerss_api_key }}"
openhab_latlon: "{{ latitude }},{{ longitude }}"

openhab_zwave_securitykey: "{{ vault_openhab_zwave_securitykey }}"

openhab_solaredge_api_key: "{{ vault_openhab_solaredge_api_key }}"
openhab_solaredge_siteId: "{{ vault_openhab_solaredge_siteId }}"

sonos_ids:
  livingroom: "{{ vault_sonos_livingroom }}"
  alfresco: "{{ vault_sonos_alfresco }}"
  portable1: "{{ vault_sonos_portable1 }}"

openhab_audio_sink: "sonos:CONNECTAMP:{{ sonos_ids.livingroom }}"

# Parameters for alarm panel
elk_ip: 172.22.2.10
elk_port: 2101

# OpenHAB Base configuration - addons.cfg
openhab_package: expert

openhab_bindings:
  - astro
  - expire1
  - gpstracker
  - mqtt
  - network
  - ntp
  - solaredge
  - sonos
  - tcp1
  - zwave

openhab_ui:
  - basic
  - paper
  - habmin
  - habpanel
  - homebuilder

openhab_action: []

openhab_persistence:
  - jdbc-postgresql
  - rrd4j
  - influxdb

openhab_transformation:
  - javascript
  - map
  - regex

openhab_voice:
  - voicerss

openhab_misc:
  - market
