---
role: Home Automation Server

# Hardening Overrides
net_ipv4_ip_forward: 1

# Postgresql
openhab_db_user: openhab2
openhab_db_password: "{{ vault_openhab_db_password }}"
openhab_db_name: openhab2
openhab_db_host: 127.0.0.1
postgresql_pgdata: /var/lib/pgsql/data

# InfluxDB
influxdb_openhab_password: "{{ vault_influxdb_openhab_password }}"

influxdb_databases:
- dbname: 'openhab'
  dbusers:
  - username: 'openhab'
    password: "{{ vault_influxdb_openhab_password }}"
    grants: ALL
  - username: 'grafana'
    password: "{{ vault_influxdb_grafana_password }}"
    grants: READ


# Grafana
grafana_admin_password: "{{ vault_grafana_admin_password }}"

# MQTT defaults
mqtt_use_ssl: true
#mqtt_broker_owntracks: false
mqtt_broker_tls_cafile: "{{ tls_cafile }}"
mqtt_broker_tls_cert: /etc/pki/tls/certs/{{ ansible_fqdn }}.pem
mqtt_broker_tls_key: /etc/pki/tls/private/{{ ansible_fqdn }}.key

mqtt_users:
  - user: openhab2
    pass: "{{ vault_openhab_mqtt_password }}"
  - user: bomxml
    pass: "{{ vault_bomxml2mqtt_pass }}"
  - user: sonoff
    pass: "{{ vault_sonoff_mqtt_password }}"

# # Get sensitive vars from the vault

openhab_voicerss_api_key: "{{ vault_openhab_voicerss_api_key }}"
openhab_latlon: "{{ latitude }},{{ longitude }}"

openhab_zwave_securitykey: "{{ vault_openhab_zwave_securitykey }}"

openhab_solaredge_api_key: "{{ vault_openhab_solaredge_api_key }}"
openhab_solaredge_siteId: "{{ vault_openhab_solaredge_siteId }}"

openhab_pushover_api_key: "{{ vault_openhab_pushover_api_key }}"
openhab_pushover_user_key1: "{{ vault_openhab_pushover_user_key1 }}"

sonos_ids:
  livingroom: "{{ vault_sonos_livingroom }}"
  alfresco: "{{ vault_sonos_alfresco }}"
  portable1: "{{ vault_sonos_portable1 }}"

openhab_audio_sink: "sonos:CONNECTAMP:{{ sonos_ids.livingroom }}"

# Parameters for alarm panel
elk_ip: 172.22.2.10
elk_port: 2101

# OpenHAB Base configuration - addons.cfg
openhab_package: expert

openhab_bindings:
  - astro
  - expire1
  - gpstracker
  - mqtt
  - network
  - ntp
  - solaredge
  - sonos
  - tcp1
  - zwave

openhab_ui:
  - basic
  - paper
  - habmin
  - habpanel
  - homebuilder

openhab_action:
  - pushover

openhab_persistence:
  - jdbc-postgresql
  - rrd4j
  - influxdb

openhab_transformation:
  - javascript
  - jsonpath
  - map
  - regex

openhab_voice:
  - voicerss

openhab_misc:
  - market
