---
# MOTD vars
role: Weather Station

weewx_location: Bungendore, NSW
weewx_latitude: -35.24798
weewx_longitude: 149.44273
weewx_altitude: 2300
weewx_altitude_units: foot
weewx_driver: Vantage

weewx_vantage_iss_id: 4
weewx_vantage_url: weatherlink.core.home.gatwards.org
weewx_vantage_tcp_port: 22222

weewx_cwop_enable: 'true'
weewx_cwop_station: VK2XJG
weewx_cwop_passcode: "{{ vault_weewx_cwop_passcode }}"

weewx_wunderground_enable: 'true'
weewx_wunderground_station: INEWSOUT867
weewx_wunderground_password: "{{ vault_weewx_wunderground_password }}"
weewx_wunderground_rapidfire: 'True'

weewx_mqtt_user: weather
weewx_mqtt_pass: "{{ vault_weewx_mqtt_pass }}"
weewx_mqtt_url: "mqtt://{{ weewx_mqtt_user }}:{{ weewx_mqtt_pass }}@automation.core.home.gatwards.org:1883/"
weewx_mqtt_topic: weather
