---
# Check if service exists for foreman
- name: "Check if foreman service exists"
  stat:
    path: "/etc/init.d/foreman"
  register: "foreman_service_file"

# Run the install of Satellite if foreman is installed
- name: "Update satellite-installer command from answers"
  set_fact:
    satellite_installer_cmd: "{{ satellite_installer_cmd }} --{{ item.key }}='{{ item.value }}'"
  with_dict: "{{ satellite_answers }}"
#  when: satellite_version == 6.2

# Run the install of Satellite 6.2
- name: "Satellite installation"
  command: "{{ satellite_installer_cmd }}"
#  when: foreman_service_file.stat.exists == True and satellite_version == 6.2
  when: foreman_service_file.stat.exists
