---

- name: check if Satellite is already running
  uri:
    url: https://localhost/katello/api/status
    method: GET
    validate_certs: False
  register: status
  ignore_errors: True

- name: set version fact
  set_fact:
    sat6chk: "{{ status.json.version }}"
  when: status.json is defined

- debug:
    var: sat6chk

# Run the install of Satellite if foreman is installed
- name: "Update satellite-installer command from answers"
  set_fact:
    satellite_installer_cmd: "{{ satellite_installer_cmd }} --{{ item.key }}='{{ item.value }}'"
  with_dict: "{{ satellite_answers }}"

- debug:
    var: satellite_answers

# Run the install of Satellite 6 when there is no response to the status API (it's not installed)
- name: "Run Satellite installer"
  command: "{{ satellite_installer_cmd }}"
  when: status.json is not defined
