---

- block:
    - name: Ensure resource pool memberships
      uri:
        url: "https://{{ ipaclient_server }}/ipa/json"
        method: POST
        validate_certs: "{{ ipaclient_validate_certs }}"
        return_content: yes
        body_format: json
        headers:
          Cookie: "{{ __auth_token }}"
          referer: "https://{{ ipaclient_server }}/ipa"
          Content-Type: application/json
          Accept: application/json
        body: >
         {
            "id": 0,
            "method": "hostgroup_add_member/1",
            "params": [
              [ "{{ item }}" ],
              {
                "host": "{{ ipaclient_hostname }}",
                "version": "{{ ipaclient_api_version }}"
              }
            ]
         }
      with_items: "{{ ipaclient_resource_pools }}"
      register: __hostgroup_add_member_resp
      failed_when: __hostgroup_add_member_resp.json.error
      changed_when: >
        __hostgroup_add_member_resp.json.result.completed is defined and
        __hostgroup_add_member_resp.json.result.completed >= 1

  rescue:
    # Clean up action. If the host does not attributed to any hostgroups
    # clean the record out of IPA.
    - name: assert attributed host
      uri:
        url: "https://{{ ipaclient_server }}/ipa/json"
        method: POST
        validate_certs: "{{ ipaclient_validate_certs }}"
        return_content: yes
        body_format: json
        headers:
          Cookie: "{{ __auth_token }}"
          referer: "https://{{ ipaclient_server }}/ipa"
          Content-Type: application/json
          Accept: application/json
        body: >
         {
            "id": 0,
            "method": "host_show/1",
            "params": [
              [ "{{ ipaclient_hostname }}" ],
              {
                "version": "{{ ipaclient_api_version }}"
              }
            ]
         }
      register: __host_show_resp
      failed_when: __host_show_resp.json.error
      changed_when: False

    - name: Remove unattributed hosts
      when: >
        __host_show_resp.json.result.result.memberof_hostgroup is not defined
      uri:
        url: "https://{{ ipaclient_server }}/ipa/json"
        method: POST
        validate_certs: "{{ ipaclient_validate_certs }}"
        return_content: yes
        body_format: json
        headers:
          Cookie: "{{ __auth_token }}"
          referer: "https://{{ ipaclient_server }}/ipa"
          Content-Type: application/json
          Accept: application/json
        body: >
         {
            "id": 0,
            "method": "host_del/1",
            "params": [
              [ "{{ ipaclient_hostname }}" ],
              {
                "version": "{{ ipaclient_api_version }}"
              }
            ]
         }
      register: __host_del_resp
      failed_when: __host_del_resp.json.error
      changed_when: __host_del_resp.json.result
      notify: enrollment failed

    - meta: flush_handlers
