---

- name: define host entity
  when: not __realm_enrolled
  uri:
    url: "https://{{ ipaclient_server }}/ipa/json"
    method: POST
    validate_certs: "{{ ipaclient_validate_certs }}"
    return_content: yes
    body_format: json
    headers:
      Cookie: "{{ __auth_token }}"
      referer: "https://{{ ipaclient_server }}/ipa"
      Content-Type: application/json
      Accept: application/json
    body: >
     {
        "id": 0,
        "method": "host_add/1",
        "params": [
          [ "{{ ipaclient_hostname }}" ],
          {
            "random": true,
            "version": "{{ ipaclient_api_version }}"
          }
        ]
     }
  register: __host_add_resp
  changed_when: not __host_add_resp.json.error
  failed_when: __host_add_resp.json.error

- name: reset host entity
  when: __realm_enrolled
  uri:
    url: "https://{{ ipaclient_server }}/ipa/json"
    method: POST
    validate_certs: "{{ ipaclient_validate_certs }}"
    return_content: yes
    body_format: json
    headers:
      Cookie: "{{ __auth_token }}"
      referer: "https://{{ ipaclient_server }}/ipa"
      Content-Type: application/json
      Accept: application/json
    body: >
     {
        "id": 0,
        "method": "host_mod/1",
        "params": [
          [ "{{ ipaclient_hostname }}" ],
          {
            "random": true,
            "version": "{{ ipaclient_api_version }}"
          }
        ]
     }
  register: __host_mod_resp
  changed_when: not __host_mod_resp.json.error
  failed_when: __host_mod_resp.json.error

  # Need to keep this on a single line.
  # Yaml Block scalar styles add either \ or \n to the end of the resulting strings.
- set_fact:
    __enrollment_secret: "{{ __host_mod_resp.json.result.result.randompassword if __realm_enrolled else __host_add_resp.json.result.result.randompassword }}"
  no_log: True
