---
- name: Install additional RPM packages
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - python2-pip
      - git
      - sshpass
      - openldap-clients


# Need to upgrade setuptools (and pip?) via pip before this will work
#- name: install manageiq-client
#  tags:
#    - install
#  pip:
#    name: manageiq-client


- name: install the last version of OpenSSL
  pip:
    name: pyOpenSSL
    state: latest

# Tower-cli from pip is a later version than python2-ansible-tower-cli RPM
- name: Install tower-cli from pip
  pip:
    name: ansible-tower-cli

- name: Install pywinrm for connecting to windows hosts
  pip:
    name: "{{ packages }}"
  vars:
    packages:
    - pywinrm>=0.2.2
    - pywinrm[kerberos]
    - pywinrm[credssp]


- name: Allow insecure git repos for self signed certificates
  command: git config --global http.sslVerify "false"

  #- name: Set git user
  #  command: git config --global user.name "{{ user_prefix }}{{ inventory_hostname | regex_replace('\\D') }}"

  #- name: Set git user email
  #  command: git config --global user.email "{{ user_prefix }}{{ inventory_hostname | regex_replace('\\D') }}@{{ ansible_domain }}"

  #- name: Set git to cache credentials
  #  command: git config --global credential.helper cache

  #- name: Update git to credential timeout after 1 day
  #  command: git config --global credential.helper 'cache --timeout=86400'



- name: check if we need to do installer things
  uri:
    url: https://localhost/api/v1/ping/
    method: GET
    user: admin
    password: "{{ tower_pass }}"
    validate_certs: False
  register: checkout
  ignore_errors: True

- name: set condtional if the above didn't error
  set_fact:
    towerchk: "{{ checkout.json.version }}"
  when: checkout.json is defined


- name: Download Ansible Tower bundle
  get_url:
    url: "{{ tower_repo_url }}/ansible-tower-setup-bundle-{{ tower_version }}.el7.tar.gz"
    dest: /tmp/ansible-tower-setup-bundle.tar.gz
  when: towerchk not in tower_version

- name: Untar Tower bundle
  unarchive:
    src: /tmp/ansible-tower-setup-bundle.tar.gz
    dest: /tmp/
    remote_src: true
    owner: root
  when: towerchk not in tower_version

# Allow other jobs to read the tower config dir. This is so that we can use the tower cert in CFME
- name: Allow access to Tower config directory
  lineinfile:
    dest: /tmp/ansible-tower-setup-bundle-{{ tower_version }}.el7/roles/awx_install/templates/settings.py.j2
    line: "AWX_PROOT_SHOW_PATHS = ['/etc/tower/']"
  when: towerchk != tower_version

- name: Stage Tower installation inventory
  template:
    src: templates/towerinventorysetup
    dest: /tmp/ansible-tower-setup-bundle-{{ tower_version }}.el7/inventory
  when: towerchk != tower_version

- name: Run the Tower installer (This will take some time)
  command: chdir=/tmp/ansible-tower-setup-bundle-{{ tower_version }}.el7 ./setup.sh
  register: towerinstall
  when: towerchk not in tower_version

- name: wait for tower to be up
  uri:
    url: https://localhost/api/v1/ping/
    method: GET
    user: admin
    password: "{{ tower_pass }}"
    validate_certs: False
    force_basic_auth: yes
  register: check2
  until: check2.json is defined and check2.json.version in tower_version
  retries: 10
  delay: 30
  when: towerchk not in tower_version

- name: Update permissions on Tower certificate
  file:
    path: /etc/tower/tower.cert
    mode: 0444
    group: root
    owner: root

- name: Deploy tower-cli config
  template:
    src: templates/tower_cli.cfg.j2
    dest: /etc/tower/tower_cli.cfg
    mode: 0600

- name: Install Tower license
  uri:
    url: https://{{ inventory_hostname }}/api/v2/config/
    method: POST
    validate_certs: no
    user: admin
    password: "{{ tower_pass }}"
    force_basic_auth: yes
    status_code: 200
    body: "{{ tower_lic }}"
    body_format: json

- name: Add LDAP Config
  uri:
    url: https://localhost/api/v2/settings/ldap/
    method: PATCH
    user: admin
    password: "{{ tower_pass }}"
    body: "{{ lookup('template','ldap_conf.json.j2') }}"
    body_format: json
    validate_certs: False
    force_basic_auth: yes

- name: Delete demo inventory
  uri:
    url:  https://localhost/api/v2/inventories/1/
    method: DELETE
    user: admin
    password: "{{ tower_pass }}"
    validate_certs: False
    force_basic_auth: yes
    status_code:
      - 200
      - 201
      - 202
      - 204
      - 400
      - 404
  register: response
  changed_when: response.status == 204

- name: Delete demo project
  uri:
    url:  https://localhost/api/v2/projects/4/
    method: DELETE
    user: admin
    password: "{{ tower_pass }}"
    validate_certs: False
    force_basic_auth: yes
    status_code:
      - 200
      - 201
      - 202
      - 204
      - 400
      - 404
  register: response
  changed_when: response.status == 204

- name: Delete demo template
  uri:
    url:  https://localhost/api/v2/job_templates/5/
    method: DELETE
    user: admin
    password: "{{ tower_pass }}"
    validate_certs: False
    force_basic_auth: yes
    status_code:
      - 200
      - 201
      - 202
      - 204
      - 400
      - 404
  register: response
  changed_when: response.status == 204

- name: Delete demo credential
  uri:
    url:  https://localhost/api/v2/credentials/1/
    method: DELETE
    user: admin
    password: "{{ tower_pass }}"
    validate_certs: False
    force_basic_auth: yes
    status_code:
      - 200
      - 201
      - 202
      - 204
      - 400
      - 404
  register: response
  changed_when: response.status == 204

- name: Add win_shell/win_feature/win_reboot to allowed adhoc modules
  uri:
    url:  https://localhost/api/v2/settings/all/
    method: PATCH
    user: admin
    password: "{{ tower_pass }}"
    body: "{{ lookup('template','tower_config_adhoc.json.j2') }}"
    body_format: json
    validate_certs: False
    force_basic_auth: yes
    status_code:
      - 200
      - 204
      - 400
  register: response
  changed_when: response.status == 200

- name: Set Base URL of Tower to resolve issues with websocket
  uri:
    url:  https://localhost/api/v2/settings/system/
    method: PATCH
    user: admin
    password: "{{ tower_pass }}"
    body: '{ "TOWER_URL_BASE": "https://{{ inventory_hostname }}" }'
    body_format: json
    validate_certs: False
    force_basic_auth: yes
    status_code:
      - 200
      - 204
      - 400
  register: response
  changed_when: response.status == 200

  #https://github.com/mgmt-sa-tiger-team/skylight/blob/master/roles/ansible-tower/tasks/setup.yml#L55


- name: Add Ansible service account
  tower_user:
    username: "{{ svc_ansible_user }}"
    password: "{{ svc_ansible_password }}"
    email: "{{ svc_ansible_email }}"
    first_name: Ansible
    last_name: Generic
    state: present


# TODO: Add user to organization


# Needed for tower_credential method
- name: Stage SSH key to temp file
  copy:
    content: "{{ svc_ansible_private_ssh_key }}"
    dest: /tmp/ssh.key

- name: add Ansible user SSH key
  tower_credential:
    name: "{{ svc_ansible_user }} SSH key"
    description: SSH key
    organization: Default
    state: present
    username: "{{ svc_ansible_user }}"
    user: "{{ svc_ansible_user }}"
    kind: ssh
    ssh_key_data: /tmp/ssh.key

- name: Stage SCM SSH key to temp file
  copy:
    content: "{{ svc_git_private_ssh_key }}"
    dest: /tmp/ssh.key

- name: add Ansible user git credentials
  tower_credential:
    name: "{{ svc_git_user }} SCM key"
    description: "SCM key"
    organization: Default
    state: present
    username: "{{ svc_git_user }}"
    user: "{{ svc_ansible_user }}"
    kind: scm
    ssh_key_data: /tmp/ssh.key

- name: add Ansible Vault credentials
  tower_credential:
    name: "vault credential"
    description: vault
    organization: Default
    state: present
    kind: vault
    vault_password: "{{ vault_password }}"

# Not currently working - https://github.com/ansible/ansible/issues/45172
#- name: Create satellite 6 credentials
#  tower_credential:
#    name: "satellite 6"
#    description: "Satellite 6"
#    organization: Default
#    state: present
#    kind: satellite6
#    username: "{{ sat6_tower_user }}"
#    password: "{{ sat6_tower_pass }}"
#    satellite_6_url: "{{ sat6_url }}"


# TODO: Give the ansible user permission to use each of the the credentials


# Add new inventory
- name: Create Satellite inventory
  tower_inventory:
    name: "satellite 6"
    description: "Satellite 6"
    organization: Default
    state: present

# Create Sat6 inventory source
- name: Setup Sat6 as an inventory source
  tower_inventory_source:
    name: "satellite 6"
    description: "Satellite 6"
    state: present
    inventory: "satellite 6"
    credential: "satellite 6"
    overwrite: true
    overwrite_vars: true
    source: satellite6
    update_cache_timeout: 0
    update_on_launch: true

# TODO: Give the ansible user permission to use and update the inventory

# Create project
- name: Create project
  tower_project:
    name: GG_Infra
    organization: Default
    scm_type: git
    scm_url: "{{ git_url }}"
    scm_branch: "{{ git_branch }}"
    scm_clean: true
    scm_credential: "{{ svc_git_user }} SCM key"
    scm_update_on_launch: true

# Checkout Project (should happen on creation - need to wait for it to complete)

# Create job templates from project
#- name: Create job template
#  tower_job_template:
