---
#The below play-book will only set up the server as a second authorisation client
# i.e. assumes that generic has been run so that it is set up as a IPA/IdM client to one auth. server

- name: 2nd auth. client - Make the server an IdM client
  become: true
  become_user: root
  hosts: all
  tags: IdM_client
  vars_files:
    - vars/auth2.yml
    - vars/IdM.yml
  tasks:
    - name: IdM client - Confirm the installation of sssd
      package:
        name: 
        - sssd
        - sssd-client
        - sssd-common
        state: present

    - name: IdM client - Set up sssd config. file = {{ sssd_conffile }}
      template:
        src: "templates/auth2_client/IdM.conf.j2"
        dest: "{{ sssd_conffile }}"
        mode: 0640
        owner: sssd
        group: sssd
        seuser: system_u
        serole: object_r
        setype: sssd_t

    - name: IdM client - Add IdM to /etc/sssd.conf
      lineinfile:
        regexp: "^domains ="
        line: "domains = {{ SecondDomain }}"
        dest: "/etc/sssd.conf"   
      notify: restart_sssd

  handlers:
    - name: 2nd auth. client - restart_sssd
      systemd:
        name: sssd
        state: restarted

- name: 2nd auth. client - Make the server an LDAP client
  become: true
  become_user: root
  hosts: all
  tags: LDAP_client
  vars_files:
    - vars/auth2.yml
    - vars/LDAP.yml
  tasks:
    - name: LDAP client - Confirm the installation of sssd
      package:
        name: 
        - sssd
        - sssd-client
        - sssd-common
        state: present

    - debug:
        msg: Make sure /etc/pki/tls/certs/ca-bundle.crt is there

    - debug:
        msg: "basedir = {{ sssd_basedir }}, confdir = {{ sssd_confdir }} & conffile = {{ sssd_conffile }}"

    - name: LDAP client - Set up sssd config. file = {{ sssd_conffile }}
    ## Need to automate "ldap_search_base = dc=example,dc=com" in {{ sssd_conffile }}
      template:
        src: "templates/auth2_client/LDAP.conf.j2"
        dest: "{{ sssd_conffile }}"
        mode: 0640
        owner: sssd
        group: sssd
        seuser: system_u
        serole: object_r
        setype: sssd_t

    - name: LDAP client - Add LDAP to /etc/sssd.conf
      lineinfile:
        regexp: "^domains ="
        line: "domains = LDAP"
        dest: "/etc/sssd.conf"   
      notify: restart_sssd

  handlers:
    - name: 2nd auth. client - restart_sssd
      systemd:
        name: sssd
        state: restarted

- name: 2nd auth. client - Make the server an AD client
  become: true
  become_user: root
  hosts: all
  tags: AD_client
  vars_files:
    - vars/auth2.yml
    - vars/AD.yml
  tasks:
    # - name: AD client - Use AD role
    #   import_role:
    #     name: ansible-role-adjoin

  - name: AD client - Install packages
    package:
      name: "{{ packages }}"
      state: present

  - name: AD client - Configure services
    template:
      dest: "{{ conffile.dest }}"
      src: "{{ conffile.src }}"
      mode: 0644
      owner: 'root'
      group: 'root'
    no_log: "{{ adjoin_no_log }}"
    loop:
      - {src: 'ldap.conf.j2', dest: "{{ openldap_conffile }}"}
      - {src: 'krb5.conf.j2', dest: '/etc/krb5.conf'}
    loop_control:
      loop_var: 'conffile'

    - name: AD client - Check AD connection with testjoin
      command: "timeout 5 /usr/bin/net ads testjoin -s /etc/samba/smb_{{ SecondDomain }}.conf"
      changed_when: false
      loop: "{{ adjoin_domains }}"
      no_log: "{{ adjoin_no_log }}"
      loop_control:
        loop_var: 'domain'

    - name: AD client - Join AD domain
      command: '/usr/bin/net ads join -s /etc/samba/smb_{{ SecondDomain }}.conf \
        -U{{ domain.username }}%{{ domain.password }} \
        osName="{{ ansible_distribution }}" \
        osVer="{{ ansible_distribution_version }}" \
        createcomputer={{ domain.computer_objects_path }}'
      no_log: "{{ adjoin_no_log }}"
      loop: "{{ adjoin_domains }}"
      loop_control:
        loop_var: 'domain'

  - name: AD client - Configure SSSD
    template:
      dest: "/etc/sssd/conf.d/{{ SecondDomain }}.conf"
      src: "sssd.conf.j2"
      mode: 0600
      owner: 'root'
      group: 'root'
    no_log: "{{ adjoin_no_log }}"
    notify:
      - reconfigure redhat pam
      - reconfigure debian pam
      - clear sssd cache

  - name: AD client - Configure services - Common
    systemd:
      name: "{{ service.name }}"
      enabled: "{{ service.enabled }}"
      masked: "{{ service.masked }}"
      state: "{{ service.state }}"
    loop:
      - {'name':'sssd', 'enabled':'yes', 'masked':'no', 'state':'started'}
      - {'name':'dbus', 'enabled':'yes', 'masked':'no', 'state':'started'}
      - {'name':'systemd-logind', 'enabled':'no', 'masked':'yes', 'state':'stopped'}
    loop_control:
      loop_var: 'service'

  - name: AD client - Configure Sudo permissions for admin users
    template:
      dest: "/etc/sudoers.d/10_linux_admins"
      src: "sudoers_10_linux_admins"
      mode: 0440
      validate: "visudo -cf %s"
      owner: 'root'
      group: 'root'
    when: adjoin_configure_sudo