---
#The below play-book will only set up the server as a second authorisation client
# i.e. assumes that generic has been run so that it is set up as a client to one auth. server

- name: 2nd auth. client - Make the server an IdM client
  become: true
  become_user: root
  hosts: all
  tags: IdM_client
  vars_files:
    - vars/IdM.yml
  tasks:
    - name: IdM client - Confirm the installation of sssd
      package:
        name: 
        - sssd
        - sssd-client
        - sssd-common
        state: present

- name: 2nd auth. client - Make the server an LDAP client
  become: true
  become_user: root
  hosts: all
  tags: LDAP_client
  vars_files:
    - vars/LDAP.yml
  tasks:
    - name: LDAP client - Confirm the installation of sssd
      package:
        name: 
        - sssd
        - sssd-client
        - sssd-common
        state: present

    - debug:
        msg: Make sure /etc/pki/tls/certs/ca-bundle.crt is there

    - debug:
        msg: "basedir = {{ sssd_basedir }}, confdir = {{ sssd_confdir }} & conffile = {{ sssd_conffile }}"

    - name: LDAP client - Set up sssd config. file = {{ sssd_conffile }}
      template:
        src: "templates/auth2_client/LDAP.conf.j2"
        dest: "{{ sssd_conffile }}"
        mode: 0640
        owner: sssd
        group: sssd
        seuser: system_u
        serole: object_r
        setype: sssd_t

- name: 2nd auth. client - Make the server an AD client
  become: true
  become_user: root
  hosts: all
  tags: AD_client
  vars_files:
    - vars/AD.yml
  tasks:
    - name: AD client - Confirm the installation of sssd
      package:
        name: 
        - sssd
        - sssd-client
        - sssd-common
        - sssd-ad
        - krb5-workstation
        state: present