---
- name: Install OpenHAB
  remote_user: svc-ansible
  become: true
  hosts: openhab
  pre_tasks:
  - name: Include vault vars
    include_vars: vault.yml
    no_log: true

  tasks:
  - name: Create HTTP service in IPA
    ipa_service:
      ipa_user: "{{ idm_admin_user }}"
      ipa_pass: "{{ idm_admin_pass }}"
      krbcanonicalname: HTTP/{{ ansible_fqdn }}
      state: present

  - name: Check if SSL certs already exist
    stat:
      path: /etc/pki/tls/certs/{{ ansible_fqdn }}.pem
    register: sslcerts
    changed_when: false

  - name: Request new SSL certs from IPA
    command: ipa-getcert request -r -g 4096 -f /etc/pki/tls/certs/{{ ansible_fqdn }}.pem -k /etc/pki/tls/private/{{ ansible_fqdn }}.key -N CN={{ ansible_fqdn }} -K HTTP/{{ ansible_fqdn }}
    when: not sslcerts.stat.exists

  - include_role:
      name: ansible-role-openhab

  - name: Add rich-rule to allow Sonos uPNP
    firewalld:
      rich_rule: 'rule family="ipv4" source address="172.22.1.0/24" destination address="239.255.255.250/32" port port="1900" protocol="udp" accept'
      immediate: yes
      permanent: yes
      state: enabled


#   - include: deploy_config.yml

# - name: Install ZWave RPi
#   remote_user: svc-ansible
#   become: true
#   hosts: zwave
#   pre_tasks:
#   - name: Include vault vars
#     include_vars: vault.yml
#     no_log: true

#   tasks:
#   - name: Install packages
#     package:
#       name: "{{ item }}"
#       state: present
#     with_items:
#       - ser2net

#   - name: Deploy ser2net config
#     template:
#       src: ser2net.conf.j2
#       dest: /etc/ser2net.conf
#       owner: root
#       group: root
#       mode: 0644
#     notify: Restart ser2net

#   - name: Install ser2net script
#     copy:
#       content: |
#         #!/bin/sh
#         /usr/sbin/ser2net -c /etc/ser2net.conf -P /run/ser2net.pid
#       dest: /usr/local/bin/ser2net.sh
#       owner: root
#       group: root
#       mode: 0755
#     notify: Restart ser2net

#   - name: Remove default ser2net init script
#     file:
#       path: /etc/init.d/ser2net
#       state: absent

#   - name: Install ser2net service
#     template:
#       src: ser2net.service.j2
#       dest: /etc/systemd/system/ser2net.service
#       owner: root
#       group: root
#       mode: 0755

#   - name: Enable services
#     service:
#       name: "{{ item }}"
#       state: started
#       enabled: true
#       daemon_reload: true
#     with_items:
#       - ser2net

#   - name: Install Z-Wave udev restart script
#     copy:
#       content: |
#         #!/bin/sh
#         systemctl restart ser2net
#       dest: /usr/local/bin/restart-zwave-replug
#       owner: root
#       group: root
#       mode: 0755

#   - name: Install Z-Wave udev rules
#     copy:
#       content: "SUBSYSTEM==\"tty\", ATTRS{idVendor}==\"0658\", ATTRS{idProduct}==\"0200\", SYMLINK+=\"zwave\", GROUP=\"dialout\", MODE=\"0666\", RUN+=\"/usr/local/bin/restart-zwave-replug\""
#       dest: /etc/udev/rules.d/99-zwave-stick.rules
#       owner: root
#       group: root
