---
# - name: Configure InfluxDB
#   remote_user: svc-ansible
#   become: true
#   hosts: influxdb
#   pre_tasks:
#   - name: Include vault vars
#     include_vars: vault.yml
#     no_log: true

#   tasks:
#   - include_role:
#       name: ansible-role-influxdb
#     tags:
#     - all
#     - openhab


- name: Install OpenHAB
  remote_user: svc-ansible
  become: true
  hosts: openhab
  pre_tasks:
  - name: Include vault vars
    include_vars: vault.yml
    no_log: true
    tags:
    - all
    - openhab
    - config
    - postgresql
    - mqtt
    - influx
    - grafana

  tasks:
  - name: Deploy script to create client certs in IPA
    copy:
      src: create_certs.sh
      dest: /usr/local/bin
      owner: root
      group: root
      mode: 0755
    tags:
    - all
    - mqtt

  - include_role:
      name: ansible-role-openhab
    tags:
    - all
    - openhab
    - config
    - postgresql
    - mqtt
    - zwave
    - influx
    - grafana

  - name: Add rich-rule to allow Sonos uPNP
    firewalld:
      rich_rule: 'rule family="ipv4" source address="172.22.1.0/24" destination address="239.255.255.250/32" port port="1900" protocol="udp" accept'
      immediate: yes
      permanent: yes
      state: enabled
    tags:
    - all
    - openhab

  - name: Add rule to allow DHCP proxy listener
    firewalld:
      port: "{{ item }}"
      immediate: yes
      permanent: yes
      state: enabled
    with_items:
#    - 67/udp
    - 6767/udp
    tags:
    - all
    - openhab

  # - name: Redirect DHCP requests to DHCP Proxy listener
  #   firewalld:
  #     rich_rule: 'rule family="ipv4" forward-port port="67" protocol="udp" to-port="6767"'
  #     immediate: yes
  #     permanent: yes
  #     state: enabled
  #   tags:
  #   - all
  #   - openhab

  - name: Install additional packages
    package:
      name: "{{ item }}"
      state: present
    with_items:
    - python2-speedtest-cli
    tags:
    - all
    - openhab

###############################################


- name: Install ZWave RPi
  remote_user: svc-ansible
  become: true
  hosts: zwave
  pre_tasks:
  - name: Include vault vars
    include_vars: vault.yml
    no_log: true
    tags:
    - all
    - zwave

  tasks:
  - name: Install packages
    package:
      name: "{{ item }}"
      state: present
    with_items:
    - ser2net
    tags:
    - all
    - zwave

  - name: Deploy ser2net config
    template:
      src: ser2net.conf.j2
      dest: /etc/ser2net.conf
      owner: root
      group: root
      mode: 0644
    notify: Restart ser2net
    tags:
    - all
    - zwave

  - name: Install ser2net script
    copy:
      content: |
        #!/bin/sh
        /usr/sbin/ser2net -c /etc/ser2net.conf -P /run/ser2net.pid
      dest: /usr/local/bin/ser2net.sh
      owner: root
      group: root
      mode: 0755
    notify: Restart ser2net
    tags:
    - all
    - zwave

  - name: Remove default ser2net init script
    file:
      path: /etc/init.d/ser2net
      state: absent
    tags:
    - all
    - zwave

  - name: Install ser2net service
    copy:
      src: automation/ser2net.service
      dest: /etc/systemd/system/ser2net.service
      owner: root
      group: root
      mode: 0755
    tags:
    - all
    - zwave

  - name: Enable services
    service:
      name: "{{ item }}"
      state: started
      enabled: true
      daemon_reload: true
    with_items:
    - ser2net
    tags:
    - all
    - zwave

  - name: Configure firewall
    firewalld:
      port: 7676/tcp
      immediate: yes
      permanent: yes
      state: enabled
    tags:
    - all
    - zwave

  - name: Install Z-Wave udev restart script
    copy:
      content: |
        #!/bin/sh
        systemctl restart ser2net
      dest: /usr/local/bin/restart-zwave-replug
      owner: root
      group: root
      mode: 0755
    tags:
    - all
    - zwave

  - name: Install Z-Wave udev rules
    copy:
      content: "SUBSYSTEM==\"tty\", ATTRS{idVendor}==\"0658\", ATTRS{idProduct}==\"0200\", SYMLINK+=\"zwave\", GROUP=\"dialout\", MODE=\"0666\", RUN+=\"/usr/local/bin/restart-zwave-replug\""
      dest: /etc/udev/rules.d/99-zwave-stick.rules
      owner: root
      group: root
    tags:
    - all
    - zwave
