---
- name: Install Workstation
  remote_user: svc-ansible
  hosts: workstations
  pre_tasks:
    - name: Include vault vars
      include_vars: vault_{{ sys_env|lower }}.yml
      no_log: true
  tasks:
  - include_role:
      name: workstation
