---
# - name: System Hardening
#   import_playbook: hardening.yml
      
# This will create a simple DNS server based on named/bind 
- name: Configure DNS Server
  become: true
  hosts: all
  tags:
  - dns
  
  tasks:
  - name: Install DNS packages
    yum:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - bind
      - bind-utils
   
  - name: Configure named - general
    template:
      src: templates/dns/named.conf.j2
      dest: /etc/named.conf
      mode: 0640
      owner: root
      group: named
      seuser: system_u
      serole: object_r
      setype: named_conf_t

  - name: Configure named - forward
    template:
      src: templates/dns/fwd.Local_FQDN.j2
      dest: /var/named/fwd.{{ Local_FQDN }}
      mode: 0640
      owner: root
      group: named
      seuser: system_u
      serole: object_r
      setype: named_conf_t

  - name: Configure named - reverse
    template:
      src: templates/dns/rvs.ClassC_LAN.j2
      dest: /var/named/rvs.{{ ClassC_LAN }}.j2
      mode: 0640
      owner: root
      group: named
      seuser: system_u
      serole: object_r
      setype: named_conf_t

  - name: Update firewall rules (service)
    firewalld:
      service: "{{ item }}"
      immediate: yes
      permanent: yes
      state: enabled
    with_items:
    - dns

  - name: Enable DNS Server
    service:
      name: named
      state: restarted
