---
# - name: System Hardening
#   import_playbook: hardening.yml
      
# This will create a simple DNS server based on named/bind 
- name: Configure DNS Server
  become: true
  hosts: naming
  tags:
  - dns
  vars_files:
  - vars/main.yml

  tasks:
  - name: Install DNS packages
    yum:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - bind
      - bind-utils

  - name: LAN fact check
    debug:
      msg: "FQDN={{ LAN.FQDN }} DNS1={{ LAN.Net.DNS1 }} DNS2={{ LAN.Net.DNS2 }} NET={{ LAN.Net.Addr }}"

  - name: Configure named - general
    template:
      src: templates/dns/named.conf.j2
      dest: /etc/named.conf
      mode: 0640
      owner: root
      group: named
      seuser: system_u
      serole: object_r
      setype: named_conf_t

  - name: Configure named - forward
    template:
      src: templates/dns/fwd.LAN.Net.Fwd.j2
      dest: /var/named/fwd.{{ LAN.FQDN }}
      mode: 0640
      owner: root
      group: named
      seuser: system_u
      serole: object_r
      setype: named_conf_t

  - name: Configure named - reverse
    template:
      src: templates/dns/rvs.LAN.Net.Rvs.j2
      dest: /var/named/rvs.{{ LAN.Net.Rvs }}
      mode: 0640
      owner: root
      group: named
      seuser: system_u
      serole: object_r
      setype: named_conf_t

  - name: Update firewall rules (service)
    firewalld:
      service: "{{ item }}"
      immediate: yes
      permanent: yes
      state: enabled
    with_items:
    - dns

  - name: Enable DNS Server
    service:
      name: named
      state: restarted
