---
- name: Generic Infrastructure
  remote_user: svc-ansible
  become: true
  hosts: all
  pre_tasks:
    - name: Include vault vars
      include_vars: vault_{{ sys_env|lower }}.yml
      no_log: true
  tasks:
    - include_role:
        name: role_generic_os

    - include_role:
        name: role_hardening
      when: skip_hardening is not defined
