---
- name: Generic Infrastructure
  remote_user: svc-ansible
  become: true
  hosts: all
  vars_files:
  - vault.yml

  tasks:
  - include_role:
      name: ansible-role-generic-os


  - include_role:
      name: ansible-role-ipaclient

  # - include_role:
  #     name: ansible-role-hardening
  #   when: skip_hardening is not defined

  - include_role:
      name: ansible-node-exporter


  - name: Ensure krb5 realms are defined
    lineinfile:
      path: /etc/krb5.conf
      insertafter: '[domain_realm]'
      line: "  {{ item }}"
    with_items:
    - '.core.home.gatwards.org = {{ idm_realm }}'
    - 'core.home.gatwards.org = {{ idm_realm }}'
    - '.lab.home.gatwards.org = {{ idm_realm }}'
    - 'lab.home.gatwards.org = {{ idm_realm }}'
