---
- name: Generic Infrastructure
  remote_user: svc-ansible
  become: true
  hosts: all
  vars_files:
  - vault.yml

  tasks:
  - import_role:
      name: ansible-generic-os
    tags:
    - generic


  - import_role:
      name: ansible-role-ipaclient
    tags:
    - generic
    - ipa
    vars:
      ipaclient_servers:
      - ipa1.ipa.home.gatwards.org
      - ipa2.ipa.home.gatwards.org
      ipaclient_domain: ipa.home.gatwards.org
      ipaclient_enroll_user: admin
      ipaclient_enroll_pass: "{{ vault_idm_admin_pass }}"

  - name: Ensure krb5 realms are defined
    lineinfile:
      path: /etc/krb5.conf
      insertafter: '[domain_realm]'
      line: "  {{ item }}"
    with_items:
    - '.core.home.gatwards.org = {{ ipaclient_domain|upper }}'
    - 'core.home.gatwards.org = {{ ipaclient_domain|upper }}'
    - '.lab.home.gatwards.org = {{ ipaclient_domain|upper }}'
    - 'lab.home.gatwards.org = {{ ipaclient_domain|upper }}'

  - name: Add NFS domain to idmap.conf
    lineinfile:
      path: /etc/idmapd.conf
      regexp: '^#?\s?Domain.*=.*'
      line: "Domain = home.gatwards.org"
      backrefs: true
      state: present


  - import_role:
      name: ansible-role-hw_vm_tools
    tags:
    - generic
    - vmtools
