---
- name: System Hardening
  become: true
  hosts: all

  tasks:
  - block:
    - block:
      - name: Apply CIS hardening for RHEL 8.0 or 8.1 via role Ansible-RHEL8-CIS-Benchmarks8
        include_role:
          name: Ansible-RHEL8-CIS-Benchmarks
        tags:
        - hardening
        - cis
        when: ansible_distribution_version < '8.2'
 
      - name: Apply CIS hardening for RHEL 8.2+ via role Ansible-RHEL8-CIS-Benchmarks8
        include_role:
          name: Ansible-RHEL8-CIS-Benchmarks
        vars:
          # See hosts_template for more details on exclusions
          cis_level_1_exclusions: ['1.2.3','1.3.1','1.8','2.2.2','2.2.7','3.4.1','3.4.2','3.4.3','3.4.4','3.4.5','4.1.3','5.4.1.1','5.3.2']
        tags:
        - hardening
        - cis
        when: ansible_distribution_version >= '8.2'
      when: ansible_distribution_major_version == '8'

    - name: Apply CIS hardening for EL7
      import_role:
        name: Ansible-RHEL7-CIS-Benchmarks
      tags:
      - hardening
      - cis
      when: ansible_distribution_major_version == '7'
    when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS'


- name: Extra System Hardening
  become: true
  hosts: all
  tasks:
  - name: Apply additional hardening
    import_role:
      name: ansible-role-extra-hardening
    tags:
    - hardening
