---
- name: System Hardening
  remote_user: svc-ansible
  become: true
  hosts: all
  vars_files:
  - vault.yml

  tasks:
  - include_role:
      name: Ansible-RHEL8-CIS-Benchmarks
    when:
    - ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS'
    - ansible_distribution_major_version == '8'

  - include_role:
      name: Ansible-RHEL7-CIS-Benchmarks
    when:
    - ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS'
    - ansible_distribution_major_version == '7'
