---
# Do all infra setups

- name: Generic Infrastructure
  hosts: all
  remote_user: root
  tasks:

  - import_tasks:
    - generic.yml
    - buildsat6.yml
    - buildtower.yml
    - buildnagios.yml
