---
# Use Hardening playbook
# - import_playbook: hardening.yml
      
- name: Configure Squid Proxy
  hosts: all
  become: yes
  tasks:
    # - name: Configure primary NIC for local network facing
    # configure /etc/sysconfig//etc/sysconfig/network-scripts/ifcfg-{{ primary_NIC_name }}
    # in particular: PROXY_METHOD="none"

    - name: Primary NIC facts
      debug:
        msg: "Name of primary NIC = {{ primary_NIC_name }}"

    # See https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html#id21 for setting up access and routes

    # - name: Configure second NIC for internet facing

    - name: Secondary NIC facts
      debug:
        msg: "Name of secondary NIC = {{ secondary_NIC_name }}"

    # - name: Configure proxy via role ansible-squid
      # include_role:
      #   name: ansible-squid

  vars:
    primary_NIC_name: "{{ ansible_default_ipv4.interface }}"
    secondary_NIC: "{{ ansible_facts | json_query('@.* | [?pciid].{key: pciid, value: device}') | last }}"
    secondary_NIC_name: "{{ secondary_NIC.value }}"
    
  vars_files:
    - vars/main.yml
    - vars/proxy_squid.yml

  tags:
  - proxy
