---
- name: Configure Squid Proxy
  hosts: proxy.leandon.local
  tasks:
    - name: Harden Server
      include_tasks: hardening.yml
      
    - name: Configure proxy via role ansible-squid
      include_role:
        name: ansible-squid
  tags:
  - proxy