---
# Use Hardening playbook
# - import_playbook: hardening.yml
      
- name: Configure Squid Proxy
  hosts: all
  become: yes
  tasks:
    - block:
      - name: Warning
        debug:
          msg: "The following play-book assumes that ALL the NICs are pre-configured."

      - name: Primary NIC details
        debug:
          msg: "Name of primary NIC: {{ NIC_facts.primary.name }} with address: {{ NIC_facts.primary.address }}"

      - name: Secondary NIC details
        debug:
          msg: "Name of secondary NIC: {{ NIC_facts.secondary.name }} with address: {{ NIC_facts.secondary.address }}"

    - name: Configure /etc/sysctl.conf for forwarding
      lineinfile:
        regexp: "^net.ipv4.ip_forward"
        line: "net.ipv4.ip_forward=1"
        dest: "/etc/sysctl.conf"   
      notify: restart_network

    - name: Configure squid
      import_role:
        name: ansible-squid

    ## See https://www.mynotepaper.com/install-and-configure-squid-proxy-on-centos
    - name: Enable all ip's on internal network
      lineinfile:
        regexp: "^acl allowed_ips"
        line: 'acl allowed_ips  src "/etc/squid/allowed_ips.txt"'
        dest: "/etc/squid/squid.conf"   
      notify: restart_squid

    - name: Enable all ip's on http from these IP addresses
      lineinfile:
        regexp: "^http_access allow allowed_ips"
        line: "http_access allow allowed_ips"
        dest: "/etc/squid/squid.conf"   
      notify: restart_squid
    
  vars_files:
    - vars/main.yml
    - vars/proxy_squid.yml

  tags:
  - proxy

  handlers:
  - name: restart_squid
    service:
      name: squid
      state: restarted
