---
# Use Hardening playbook
# - import_playbook: hardening.yml
      
- name: Configure Squid Proxy
  hosts: all
  become: yes
  tasks:
    - name: Primary NIC name
      debug:
        msg: "Name of primary NIC = {{ primary_NIC_name }}"

    - name: Secondary NIC name
      debug:
        msg: "Name of secondary NIC = {{ secondary_NIC_name }}"

    - name: Configure /etc/sysctl.conf for forwarding
      lineinfile:
        regexp: "^net.ipv4.ip_forward"
        line: "net.ipv4.ip_forward=1"
        dest: "/etc/sysctl.conf"   
      notify: restart_network

    # - name: Configure proxy via role ansible-squid
      # include_role:
      #   name: ansible-squid

  vars:
    primary_NIC_name: "{{ ansible_default_ipv4.interface }}"
    secondary_NIC: "{{ ansible_facts | json_query('@.* | [?pciid].{key: pciid, value: device}') | last }}"
    secondary_NIC_name: "{{ secondary_NIC.value }}"
    
  vars_files:
    - vars/main.yml
    - vars/proxy_squid.yml

  tags:
  - proxy
