---
- name: Install Tang NDBE Servers
  remote_user: svc-ansible
  become: true
  hosts: tang
  # pre_tasks:
  #   - name: Include vault vars
  #     include_vars: vault.yml
  #     no_log: true

  tasks:
  - name: Install required packages
    yum:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
        - tang

  - name: Enable service
    service:
      name: tangd.socket
      state: started
      enabled: true

  - name: Configure firewall
    firewalld:
      service: http
      immediate: true
      permanent: true
      state: enabled
