---
- name: Install Weather Servers
  remote_user: svc-ansible
  become: true
  hosts: weather
  pre_tasks:
    - name: Include vault vars
      include_vars: vault_{{ sys_env|lower }}.yml
      no_log: true
  tasks:
  - include_role:
      name: role_gg_weewx
