---
- name: Install Weather Servers
  remote_user: svc-ansible
  become: true
  hosts: weather
  vars_files:
  - vault.yml
  tasks:

  - import_role:
      name: ansible-role-weewx
    tags:
    - weather
    vars:
      weewx_location: Bungendore, NSW
      weewx_latitude: "{{ latitude }}"
      weewx_longitude: "{{ longitude }}"
      weewx_altitude: 2300
      weewx_altitude_units: foot
      weewx_driver: Vantage
      weewx_vantage_iss_id: 4
      weewx_vantage_url: weatherlink.core.home.gatwards.org
      weewx_vantage_tcp_port: 22222
      weewx_cwop_enable: 'true'
      weewx_cwop_station: VK2XJG
      weewx_cwop_passcode: "{{ vault_weewx_cwop_passcode }}"
      weewx_wunderground_enable: 'true'
      weewx_wunderground_station: INEWSOUT867
      weewx_wunderground_password: "{{ vault_weewx_wunderground_password }}"
      weewx_wunderground_rapidfire: 'True'
      weewx_use_mqtt: true
      weewx_use_mqtt_ssl: false
      weewx_mqtt_tls_cafile: "{{ tls_cafile }}"
      weewx_mqtt_tls_cert: /etc/pki/tls/certs/{{ ansible_fqdn }}.pem
      weewx_mqtt_tls_key: /etc/pki/tls/private/{{ ansible_fqdn }}.key
      weewx_mqtt_url: "mqtt://{{ mqtt_broker_fqdn }}:{{ mqtt_broker_port }}/"
      weewx_mqtt_topic: weather/weewx

  - name: Deploy custom MQTT scripts
    tags:
    - weather
    - mqtt
    template:
      src: bomxml2mqtt.py.j2
      dest: /usr/local/bin/bomxml2mqtt.py
      owner: root
      group: root
      mode: 0755

  - name: Deploy custom cron
    tags:
    - weather
    cron:
      name: bomxml
      cron_file: bomxml
      hour: '0,3,6,9,12,15,18,21'
      minute: '02'
      job: '/usr/local/bin/bomxml2mqtt.py >/dev/null 2>&1'
      state: present
      user: root

# TODO:
# /var/www/html/stormvue for TS tracking (TAR bundle from Boltek)
# Requires also vsftpd with stormvue user
