---
- name: Install Workstation
  remote_user: svc-ansible
  become: true
  hosts: workstation
  pre_tasks:
  - name: Include vault vars
    include_vars: vault.yml
    no_log: true

  tasks:
  - include_role:
      name: ansible-role-workstation
