---
- src: https://github.com/ggatward/role_generic_os.git
  scm: git
  version: development

- src: https://github.com/ggatward/role_hardening.git
  scm: git
  version: development

- src: https://github.com/ggatward/role_nagios_client.git
  scm: git
  version: development

- src: https://github.com/ggatward/ansible-role-ansibletower
  scm: git
  version: development

- src: https://github.com/ggatward/ansible-role-sat6
  scm: git
  version: development

- src: https://github.com/ggatward/ansible-role-workstation
  scm: git
  version: development

- src: https://github.com/ggatward/ansible-role-nagiosxi
  scm: git
  version: development

- src: https://github.com/ggatward/ansible-role-weewx
  scm: git
  version: development
