---
roles:
- src: https://github.com/ggatward/ansible-role-generic-os.git
  scm: git

- src: https://github.com/adfinis-sygroup/ansible-role-hw_vm_tools.git
  scm: git

- src: https://github.com/ggatward/ansible-role-hardening.git
  scm: git

- src: https://github.com/ggatward/linux_adbinding.git
  scm: git

- src: https://github.com/ggatward/Ansible-RHEL7-CIS-Benchmarks.git
  scm: git

- src: https://github.com/ggatward/Ansible-RHEL8-CIS-Benchmarks.git
  scm: git

# - src: git@github.com:ggatward/ansible-role-workstation.git
#   scm: git
#   version: development

- src: git@github.com:ggatward/ansible-role-weewx.git
  scm: git
  version: development

# - src: git@github.com:ggatward/ansible-role-openhab.git
#   scm: git
#   version: development

- src: https://github.com/ggatward/ansible-influxdb.git
  scm: git

- src: https://github.com/ggatward/ansible-prometheus.git
  scm: git

- src: https://github.com/ggatward/ansible-grafana.git
  scm: git
