---

- name: Create network mountpoints
  become_user: geoff
  file:
    path: /home/geoff/{{ item }}
    state: directory
  with_items:
    - nas_home
    - nas_mounts/Multimedia
    - nas_mounts/Software

# Mount NAS homedir  (deploy sudoers, update bashrc)
# - name: Deploy sudoers rule for mounting


# - name: Add network mounts to bash profile
#   lineinfile:
#     path: /home/geoff/.bashrc
#     line: "if [ $(mount | grep -c nas_home) -eq 0 ]; then sudo /usr/bin/mount nas1:/volume1/homes/geoff /home/geoff/nas_home; fi"
#     state: present


# Create symlinks



# VSCode configuration
- block:
  - name: List existing VSCode plugins
    become_user: geoff
    shell: "code --list-extensions"
    register: code_ext
    changed_when: false

  - name: Install VSCode plugins
    become_user: geoff
    shell: "code --install-extension {{ item }}"
    with_items:
      - dhoeric.ansible-vault
      - file-icons.file-icons
      - Gruntfuggly.todo-tree
      - haaaad.ansible
      - humao.rest-client
      - jetmartin.bats
      - jpogran.puppet-vscode
      - ms-python.python
      - openhab.openhab
      - redhat.vscode-yaml
      - Skorfulose.splunk
      - vscoss.vscode-ansible
    when: item not in code_ext.stdout

  - name: Create VSCode config dir
    become_user: geoff
    file:
      path: /home/geoff/.config/Code/User
      state: directory
      owner: geoff
      group: geoff

  - name: Deploy VSCode config
    become_user: geoff
    copy:
      src: settings.json
      dest: /home/geoff/.config/Code/User/settings.json
      owner: geoff
      group: geoff
  when: install_vscode
