---
- include: configure_auth.yml

- name: Import additional repo GPG keys
  rpm_key:
    key: https://packages.microsoft.com/keys/microsoft.asc
    state: present
    validate_certs: yes

- name: Deploy additional repo configs
  copy:
    src: vscode.repo
    dest: /etc/yum.repos.d/vscode.repo
    owner: root
    group: root
    mode: 0644

- name: Install workstation packages
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - git
      - terminator
      - code
      - rdesktop

- name: Install extra repos and packages for Fedora
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-29.noarch.rpm"
      - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-29.noarch.rpm"
      - vlc
  when: ansible_distribution == 'Fedora'

- name: Remove packages
  yum:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
      - gnome-initial-setup

- name: Create skel directories
  file:
    path: /etc/skel/.bash/git-aware-prompt
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Copy git-aware-prompt to skel
  copy:
    src: "{{ item }}"
    dest: /etc/skel/.bash/git-aware-prompt
  with_fileglob: "git-aware-prompt/*"

- name: Deploy default bashrc to skel
  copy:
    src: bashrc
    dest: /etc/skel/.bashrc
    mode: 0644
    owner: root
    group: root

# Printer setup
- block:
  - name: Deploy printer PPD
    copy:
      src: FUJI-XEROX-DocuPrint-CM305-df.ppd
      dest: /etc/cups/ppd/
      owner: root
      group: lp
      mode: 0640

  - name: Configure printer
    copy:
      src: printers.conf
      dest: /etc/cups/printers.conf
      owner: root
      group: lp
      mode: 0600
    notify: restart_cups
  when: configure_printer

# Include user specific setups
- include: geoff.yml
