---
# tasks file for ansible-generic-os

- name: Install common hardware utils
  package:
    name: "{{ packages }}"
    state: present
  when: ansible_virtualization_type == 'host'
  vars:
    packages:
      - pciutils
      - usbutils

- name: Deploy MOTD
  template:
    src: templates/motd.j2
    dest: /etc/motd
    mode: 0644
    owner: root
    group: root
