---
# handlers file for juliovp01.ansible_satellite6
# - name: restart apache
#   service:
#     name: httpd
#     state: restarted

- name: restart_postfix
  service:
    name: postfix
    state: restarted

- name: restart_cups
  service:
    name: cups
    state: restarted

- name: reboot
  reboot:
