---

ipaclient_install_command: /usr/sbin/ipa-client-install
ipaclient_automount_command: /usr/sbin/ipa-client-automount
ipa_client_host_default: /etc/ipa/default.conf

ipaclient_auth_config: /usr/sbin/authconfig

ipaclient_packages:
  ipa-client:
    state: installed
  libselinux-python:
    state: installed
