---
- name: Install grafana repo
  tags:
  - all
  - grafana
  yum_repository:
    name: grafana
    description: Grafana Repository
    baseurl: https://packages.grafana.com/oss/rpm
    enabled: true
    gpgcheck: true
    gpgkey: https://packages.grafana.com/gpg.key

- name: Install RPM packages
  tags:
  - all
  - grafana
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - grafana

- name: Open Firewall Ports
  tags:
  - all
  - grafana
  firewalld:
    port: "{{ item }}"
    immediate: yes
    permanent: yes
    state: enabled
  with_items:
  - 3000/tcp

- name: Deploy grafana configuration
  tags:
  - all
  - grafana
  template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
    owner: root
    group: grafana
    mode: 0640
  notify: Restart Grafana

- name: Enable grafana service
  tags:
  - all
  - grafana
  service:
    name: grafana-server
    state: started
    enabled: true

- name: Set grafana admin password
  tags:
  - all
  - grafana
  command: grafana-cli admin reset-admin-password '{{ grafana_admin_password }}'

# - name: Install grafana plugins
#   tags:
#   - all
#   - grafana
#   grafana_plugin:
#     name: "{{ item }}"
#     state: present
#   with_items:
#   - "{{ grafana_plugins }}"
#   notify: Restart Grafana

- name: Enable InfluxDB datasource
  tags:
  - all
  - grafana
  grafana_datasource:
    name: openhab
    grafana_url: http://localhost:3000
    grafana_user: admin
    grafana_password: "{{ grafana_admin_password }}"
    ds_type: influxdb
    ds_url: http://localhost:8086
    database: openhab_db
    time_interval: ">10s"
    basic_auth_user: grafana
    basic_auth_password: "{{ openhab_grafana_influx_password }}"

# - name: Create initial dashboard
#   tags:
#   - all
#   - grafana
#   grafana_dashboard:
