
- name: Install RPM packages
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - python-paho-mqtt
    - mosquitto
  tags:
  - all
  - mqtt

# Initialise and Configure Mosquitto (MQTT)
- name: Configure Mosquitto MQTT Broker
  template:
    src: mosquitto.conf.j2
    dest: /etc/mosquitto/mosquitto.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart MQTT
  tags:
  - all
  - mqtt

- name: Check for Mosquitto pwfile
  stat: path=/etc/mosquitto/pwfile
  register: mqtt_pwfile
  failed_when: false
  tags:
  - all
  - mqtt

- name: Create Mosquitto password file
  file:
    dest: /etc/mosquitto/pwfile
    state: touch
    owner: root
    group: root
    mode: 0644
  when: mqtt_pwfile.stat.exists is not defined or not mqtt_pwfile.stat.exists
  tags:
  - all
  - mqtt

# TODO: Add user if not defined in file
- name: Add Mosquitto user accounts
  shell: mosquitto_passwd -b /etc/mosquitto/pwfile {{ item.user }} '{{ item.pass }}'
  with_items:
    - "{{ mqtt_users }}"
  when: mqtt_pwfile.stat.exists is not defined or not mqtt_pwfile.stat.exists
  no_log: true
  notify: Restart MQTT
  tags:
  - all
  - mqtt

- name: Create Mosquitto log directory
  file:
    path: /var/log/mosquitto
    state: directory
  tags:
  - all
  - mqtt

- name: Redirect Mosquitto logs
  copy:
    content: |
      :programname,isequal,"mosquitto" /var/log/mosquitto/mosquitto.log
      & stop
    dest: /etc/rsyslog.d/mosquitto.conf
  notify: Restart rsyslog
  tags:
  - all
  - mqtt

- name: Add Mosquitto logrotate
  copy:
    content: |
      /var/log/mosquitto/*.log {
        daily
        missingok
        rotate 7
        compress
        sharedscripts
        postrotate
          /bin/kill -HUP `cat /var/run/syslogd.pid 2> /dev/null` 2> /dev/null || true
        endscript
      }
    dest: /etc/logrotate.d/mosquitto
  tags:
  - all
  - mqtt

- name: Open Firewall Ports
  firewalld:
    port: "{{ item }}"
    immediate: yes
    permanent: yes
    state: enabled
  with_items:
  - 1883/tcp
  - 8883/tcp
  - 8083/tcp
  tags:
  - all
  - mqtt

- name: Enable services
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items:
  - mosquitto
  tags:
  - all
  - mqtt
