
- name: Install openhab repo
  yum_repository:
    name: openhab
    description: openHAB 2.x Stable
    baseurl: https://dl.bintray.com/openhab/rpm-repo2/stable
    enabled: true
    gpgcheck: true
    gpgkey: https://bintray.com/user/downloadSubjectPublicKey?username=openhab
  tags:
  - openhab

- name: Install RPM packages
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - java-1.8.0-openjdk
    - python-psycopg2
    - openhab2
    - python-pip
    - httpd-tools
  tags:
  - openhab

- name: Install PIP packages
  pip:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - speedtest-cli
    - APScheduler
  tags:
  - openhab

- name: Open Firewall Ports
  firewalld:
    port: "{{ item }}"
    immediate: yes
    permanent: yes
    state: enabled
  with_items:
  - 8080/tcp
  - 1900/udp
  tags:
  - openhab

- name: Open Firewall Services
  firewalld:
    service: "{{ item }}"
    immediate: yes
    permanent: yes
    state: enabled
  with_items:
    - upnp-client
    - http
    - https
  tags:
  - openhab

# - name: Configure Nginx proxy
#   template:
#     src: nginx.conf.j2
#     dest: /etc/nginx/nginx.conf
#     owner: root
#     group: root
#     mode: 0644
#   notify: Restart nginx
#   tags:
#   - all
#   - openhab

- name: Set SELinux bools
  seboolean:
    name: httpd_can_network_connect
    persistent: true
    state: true
  tags:
  - openhab

- name: Enable services
  service:
    name: "{{ item }}"
    state: started
    enabled: true
    daemon_reload: true
  with_items:
  - openhab2
  tags:
  - openhab
