
- name: Install RPM packages
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - socat
  tags:
  - all
  - zwave

# ZWave prep
- name: Add openhab user to tty group
  user:
    name: openhab
    groups: tty
    append: yes
  tags:
  - all
  - zwave

- name: Allow openhab2 access to zwave symlink
  lineinfile:
    path: /etc/default/openhab2
    regexp: "^EXTRA_JAVA_OPTS="
    line: EXTRA_JAVA_OPTS="-Dgnu.io.rxtx.SerialPorts=/dev/zwave"
  notify: Restart Openhab
  tags:
  - all
  - zwave

- name: Install socat script
  copy:
    content: |
      #!/bin/sh
      echo $$ > /var/run/socat.pid
      /usr/bin/socat -d -d -d -ly pty,link=/dev/zwave,raw,user=openhab,group=tty,mode=777 tcp:{{ lookup('dig', groups['zwave'][0]) }}:7676,forever,interval=5
    dest: /usr/local/bin/socat.sh
    owner: root
    group: root
    mode: 0755
  notify: Restart socat
  tags:
  - all
  - zwave

- name: Install socat service
  template:
    src: socat.service.j2
    dest: /etc/systemd/system/socat.service
    owner: root
    group: root
    mode: 0755
  tags:
  - all
  - zwave

- name: Enable services
  service:
    name: socat
    state: started
    enabled: true
  tags:
  - all
  - zwave
