---

- name: Create HTTP service in IPA
  ipa_service:
    ipa_user: "{{ idm_admin_user }}"
    ipa_pass: "{{ idm_admin_pass }}"
    krbcanonicalname: HTTP/{{ ansible_fqdn }}
    state: present
  tags:
  - all


- name: Check if SSL certs already exist
  stat:
    path: /etc/pki/tls/certs/{{ ansible_fqdn }}.pem
  register: sslcerts
  changed_when: false
  tags:
  - all

# TODO: Additional SANs
- name: Request new SSL certs from IPA
  command: ipa-getcert request -r -g {{ ssl_keylen }} -f /etc/pki/tls/certs/{{ ansible_fqdn }}.pem -k /etc/pki/tls/private/{{ ansible_fqdn }}.key -N CN={{ ansible_fqdn }} -K HTTP/{{ ansible_fqdn }}
  when: not sslcerts.stat.exists
  tags:
  - all

- name: Wait for certs to be retrieved
  wait_for:
    path: /etc/pki/tls/certs/{{ ansible_fqdn }}.pem
  when: not sslcerts.stat.exists

- name: Set permissions on SSL certs
  file:
    path: "{{ item.path }}"
    mode: "{{ item.perms }}"
  with_items:
  - path: /etc/pki/tls/certs/{{ ansible_fqdn }}.pem
    perms: '0644'
  - path: /etc/pki/tls/private/{{ ansible_fqdn }}.key
    perms: '{{ ssl_key_mode }}'
