---
#env: prod
#project: stincaas
#domain: example.org
#netmask: 255.255.255.0
#network: 192.168.122.0
#broadcast: 192.168.122.255
#gateway: 192.168.122.1
#root_password: "{{ vault_root_password }}"
#cloud_pubkey: "{{ vault_cloud_pubkey }}"
#ntpservers:
#  - 0.pool.ntp.org
#  - 1.pool.ntp.org
#  - 2.pool.ntp.org

# Tower deployment vars
tower_pass: "{{ vault_tower_pass }}"
tower_version: 3.2.6-1
tower_lic: "{{ vault_tower_lic }}"
#git_pass: "{{ vault_git_pass }}"
#git_url: "https://github.com/ggatward/rh-mgmt-installer.git"
#git_url: "git@github.com:ggatward/rh-mgmt-installer.git"
git_branch: "master"
svc_user: svc-tower
svc_password: "{{ vault_svc_password }}"
svc_email: noreply@lab.gatwards.org
private_key: "{{ vault_private_key }}"
#public_key: "{{ vault_public_key }}"
#vault_password: "{{ vault_vault_password }}"
#enable_telemetry_basic_auth: "true"


# Sat6 deployment vars
satellite_fqdn: sat6.lab.home.gatwards.org
satellite_deployment_organization: "Red Hat"
satellite_deployment_location: "Canberra"
satellite_deployment_admin_password: "{{ vault_satellite_deployment_admin_password }}"
#rhn_pass: "{{ vault_rhn_pass }}"
#rhn_user: "{{ vault_rhn_user }}"
satellite_deployment_rhn_user: ggatward@redhat.com
satellite_deployment_rhn_password: "{{ vault_satellite_deployment_rhn_password }}"
satellite_register_with_rhn: true

# answers:
# specify answers key: value without -- prefix. Keys you can get when you
# use satellite-installer with --help | less for easier finding
satellite_deployment_answers:
  foreman-proxy-bmc: "true"
  foreman-proxy-bmc-default-provider: "freeipmi"
  foreman-proxy-dns: "true"
  foreman-proxy-dns-managed: "true"
  foreman-proxy-dns-interface: "eth0"
  foreman-proxy-dns-zone: "lab6.home.gatwards.org"
  foreman-proxy-dns-forwarders: "172.22.1.91; 172.22.1.92"
  foreman-proxy-dns-reverse: "6.22.172.in-addr.arpa"
  foreman-proxy-dhcp: "true"
  foreman-proxy-dhcp-managed: "true"
  foreman-proxy-dhcp-interface: eth0
  foreman-proxy-dhcp-range: "172.22.4.240 172.22.4.250"
  foreman-proxy-dhcp-gateway: 172.22.4.1
  foreman-proxy-dhcp-nameservers: 172.22.4.31
  foreman-proxy-tftp: "true"
  foreman-proxy-tftp-managed: "true"



nagios_version: 5.5.2-1
