---
# https://assets.nagios.com/downloads/nagiosxi/docs/Installing_Nagios_XI_in_an_Offline_Environment.pdf

- name: Create installation directories
  file:
    path: /tmp/rpms
    state: directory

- name: get Nagios XI bundle
  tags:
    - install
  get_url:
    url: https://repo.nagios.com/nagiosxi-offline/nagiosxi-{{ nagios_version }}.el7.x86_64.tar.gz
    dest: /tmp/rpms/xi.tar.gz

- name: untar Nagios XI bundle
  tags:
    - install
  unarchive:
    src: /tmp/rpms/xi.tar.gz
    dest: /tmp/rpms
    remote_src: true
    owner: root

- name: Install Nagios XI offline dependencies from RHEL Optional
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - dejavu-lgc-sans-fonts
    - dejavu-lgc-sans-mono-fonts
    - graphviz-gd
    - perl-Crypt-DES
    - perl-Parse-RecDescent
    - php-mbstring
    - php-snmp

- name: Install Nagios XI
  command: ./fullinstall
  args:
    chdir: /tmp/rpms/nagiosxi
    creates: /usr/local/nagios/bin/nagios

- name: Open firewall ports
  firewalld:
    service: "{{ item }}"
    state: enabled
    immediate: true
    permanent: yes
  with_items:
    - http
    - https

# At this point it seems that you need to interact with the web interface to complete the install :(
